name: Deploy JSON to GitHub Pages

on:
  push:
    branches:
      - main
      - deployment
    paths:
      - "kb/*.json"

env:
  JSON_DIR: kb
  JSON_FILE: knowledgebase.json

jobs:
  deploy-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Copy root knowledgebase.json to kb/
        run: |
          mkdir -p ${{ env.JSON_DIR }}
          cp ${{ env.JSON_FILE }} ${{ env.JSON_DIR }}/${{ env.JSON_FILE }}

      - name: Deploy JSON to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PAT_TOKEN_CIRCASSIANDNA }}
          publish_dir: ${{ env.JSON_DIR }}
          commit_message: "Deploy JSON files to GitHub Pages"
          destination_dir: ${{ env.JSON_DIR }}
